spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/filters_db"
    username: postgres
    password: admin
    driver-class-name:
      org.postgresql.Driver
